name: SCSwap
version: '${project.version}'
main: com.github.arcoda.SCSwap.SCSwap
api-version: 1.19
authors: [Arcoda]
depend: [Multiverse-Core, Multiverse-Portals, LuckPerms, NametagEdit]
description: 'Plugin for Creative/Survival server hybrid'
website: 'https://github.com/Arcoda/SCSwap'
commands:
  smp:
    description: Teleport player to the SMP part of the server
  cmp:
    description: Teleport player to the CMP part of the server
  block:
    description: Blocks/Unblocks someone from going into the SMP.
    permission: server.operator
  scswap:
    description: Control SCSwap
