name: SCSwap
version: '${project.version}'
main: io.github.arcoda.SCSwap.SCSwap
api-version: 1.19
authors: [Arcoda]
depend: [Multiverse-Core, Multiverse-Portals, LuckPerms]
description: 'Plugin for Creative/Survival server hybrid'